version: '3.8'
services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo
    volumes:
      - .:/app
  mongo:
    image: mongo:latest
    container_name: mongodb-order
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
