version: '3.8'
services:
  web:
    build: .
    container_name: order-service
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo
    volumes:
      - .:/app
  mongo:
    image: mongo:latest
    container_name: mongodb-order
    ports:
      - "27018:27017"  # Change host port to 27018 (or any other free port)
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
