version: '3.8'
services:
  web:
    build: .
    container_name: inventory_service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo
    volumes:
      - .:/app
  mongo:
    image: mongo:latest
    container_name: mongodb_inventory
    ports:
      - "27018:27017"  # Changed the host port to 27018
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
