apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory_service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory_service
  template:
    metadata:
      labels:
        app: inventory_service
    spec:
      containers:
        - name: inventory_service
          image: inventory_service:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb_inventory:27017/inventory_db"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory_service
spec:
  selector:
    app: inventory_service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
