apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb_inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb_inventory
  template:
    metadata:
      labels:
        app: mongodb_inventory
    spec:
      containers:
        - name: mongodb_inventory
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb_inventory_data
              mountPath: /data/db
      volumes:
        - name: mongodb_inventory_data
          persistentVolumeClaim:
            claimName: mongodb_inventory_pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb_inventory
spec:
  selector:
    app: mongodb_inventory
  ports:
    - port: 27017
      targetPort: 27017
