apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-inventory
  template:
    metadata:
      labels:
        app: mongodb-inventory
    spec:
      containers:
        - name: mongodb-inventory
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-inventory-data
              mountPath: /data/db
      volumes:
        - name: mongodb-inventory-data
          persistentVolumeClaim:
            claimName: mongodb-inventory-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-inventory
spec:
  selector:
    app: mongodb-inventory
  ports:
    - port: 27017
      targetPort: 27017
