apiVersion: apps/v1
kind: Deployment
metadata:
  name: order_service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order_service
  template:
    metadata:
      labels:
        app: order_service
    spec:
      containers:
        - name: order_service
          image: order_service:latest
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb_order:27017/orders_db"
---
apiVersion: v1
kind: Service
metadata:
  name: order_service
spec:
  selector:
    app: order_service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
