apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb_order_pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb_order
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb_order_pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb_inventory_pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb_inventory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb_inventory_pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
