apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-order-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb-order
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-order-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-inventory-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb-inventory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-inventory-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
